<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>RulePattern.Notify</PackageId>
        <Version>1.0.1</Version>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\RulePattern\RulePattern.csproj" />
    </ItemGroup>
</Project>
